<?php

use Bitweaver\KernelTools;

//This holds the checkbox options for what to display on the 'list galleries' page
$formGalleryGeneral = [
	"fisheye_menu_text" => [
		'label' => 'Menu Text',
		'note' => '',
		'type' => 'text',
	],
/* Disabled for now - spiderr
	"feature_megaupload" => [
		'label' => 'Use <a href="http://sourceforge.net/projects/megaupload">MegaUpload</a>',
		'note' => 'Upload progress meter that requires Perl and ExecCGI permission',
		'type' => 'checkbox'
	],
*/
	"liberty_offline_thumbnailer" => [
		'label' => 'Background Thumbnailer',
		'note' => 'Thumbnails will be queued and regenerated by a background command-line script. For more information, see '.FISHEYE_PKG_PATH.'thumbaniler.php or you can <a href="'.FISHEYE_PKG_URL.'thumbnailer.php">run it manually</a>',
		'type' => 'checkbox',
	],
	"fisheye_show_public_on_upload" => [
		'label' => 'Show Public Galleries on Upload',
		'note' => 'Enable this if you want to have all public galleries visible when uploading files. This might cause problems on large sites with many public galleries.',
		'type' => 'checkbox',
	],
	"fisheye_show_all_to_admins" => [
		'label' => 'Show all Galleries to Administrators',
		'note' => 'This will allow gallery admins to upload and move around images in all galleries. This might cause problems on large sites with many galleries.',
		'type' => 'checkbox',
	],
	"fisheye_disk_storage_root" => [
		'label' => 'External Disk Storage Path',
		'note' => 'Filesystem path an external media library (e.g. a film collection) lives under. Used by mime plugins that register files already on disk without copying them into storage/attachments/. Include a trailing slash.',
		'type' => 'text',
	],
	"fisheye_tvshow_storage_root_am" => [
		'label' => 'TV Show Storage Path (A-M)',
		'note' => 'Filesystem path for TV shows whose title starts A-M, if the library is split across two roots. Leave blank if TV shows live under the single External Disk Storage Path above instead. Include a trailing slash.',
		'type' => 'text',
	],
	"fisheye_tvshow_storage_root_nz" => [
		'label' => 'TV Show Storage Path (N-Z)',
		'note' => 'Filesystem path for TV shows whose title starts N-Z - see the A-M path above.',
		'type' => 'text',
	],
];
if( !$gBitSystem->isPackageActive( 'gigaupload' ) ) {
	$formGalleryGeneral["fisheye_extended_upload_slots"] = [
		'label' => 'Extended Upload Slots',
		'note' => 'When you enable this, users can enter the title and description of the file when uploading them.',
		'type' => 'checkbox',
	];
};
$gBitSmarty->assign('formGalleryGeneral', $formGalleryGeneral);

$formGalleryListLists = [
	"fisheye_list_title" => [
		'label' => 'Gallery title',
		'note' => 'List the title of the gallery.',
	],
	"fisheye_list_thumbnail" => [
		'label' => 'Thumbnail',
		'note' => 'Display a small thumbnail associated with a gallery',
	],
	"fisheye_list_description" => [
		'label' => 'Description',
		'note' => 'List the description of a gallery',
	],
	"fisheye_list_user" => [
		'label' => 'Creator',
		'note' => 'List the name of the user who created the gallery',
	],
	"fisheye_list_hits" => [
		'label' => 'Hits',
		'note' => 'List number of hits this gallery has receieved',
	],
	"fisheye_list_created" => [
		'label' => 'Creation date',
		'note' => 'List the creation date of the gallery',
	],
	"fisheye_list_lastmodif" => [
		'label' => 'Last modification',
		'note' => 'List date this gallery was last modified',
	],
];
$gBitSmarty->assign('formGalleryListLists', $formGalleryListLists);

// This holds the checkbox options for what to display on a 'view gallery' page
$formGalleryLists = [
	"fisheye_gallery_list_title" => [
		'label' => 'Gallery title',
		'note' => 'When viewing a gallery, display the title of the gallery',
	],
	"fisheye_gallery_list_description" => [
		'label' => 'Gallery description',
		'note' => 'When viewing a gallery, display the description of the gallery below the title',
	],
	"fisheye_gallery_list_image_titles" => [
		'label' => 'Image titles',
		'note' => 'Show image titles underneath each thumbnail',
	],
	"fisheye_gallery_hide_modules" => [
		'label' => 'Hide modules for galleries',
		'note' => 'When viewing a gallery, hide the left and right module columns',
	],
	"fisheye_gallery_list_image_descriptions" => [
		'label' => 'Image description',
		'note' => 'Show image descriptions underneath each thumbnail',
	],
	"fisheye_gallery_div_layout" => [
		'label' => '&lt;div&gt; based Layout',
		'note' => 'You can use a &lt;div&gt; based layout, which will adjust the number of images in each row to the width of the browser. Please visit the online help for more information.',
		'page' => 'FisheyePackage',
	],
];
$gBitSmarty->assign( 'formGalleryLists',$formGalleryLists );

// This holds the checkbox options for what to display on an 'image details' page
$formImageLists = [
	"fisheye_image_list_title" => [
		'label' => 'Image title',
		'note' => 'When viewing an image, display the title of the image',
	],
	"fisheye_image_list_description" => [
		'label' => 'Image description',
		'note' => 'When viewing an image, display the description of the image below the title',
	],
	"fisheye_image_hide_modules" => [
		'label' => 'Hide modules for images',
		'note' => 'When viewing an image, hide the left and right module columns',
	],
	"gallerybar_use_icons" => [
		'label' => 'Use icons in the gallery bar',
		'note' => 'When viewing an image, show <strong>previous</strong> and <strong>next</strong> links as images instead of words',
	],
	"gallery_bar_use_thumbnails" => [
		'label' => 'Use Thumbnails in gallery bar',
		'note' => 'When viewing an image, show previous and next <strong>thumbnails</strong> with the appropriate links.',
	],
];
$gBitSmarty->assign( 'formImageLists', $formImageLists);

use Bitweaver\Fisheye\FisheyeGallery;

$gBitSmarty->assign( 'galleryPaginationTypes', FisheyeGallery::getAllLayouts() );

$sortOptions = [
	''                      => KernelTools::tra( 'None' ),
	'lc.title_desc'         => KernelTools::tra( 'Image Title' ).  ' - '.KernelTools::tra( 'descending' ),
	'lc.title_asc'          => KernelTools::tra( 'Image Title' ).  ' - '.KernelTools::tra( 'ascending' ),
	'lc.created_desc'       => KernelTools::tra( 'Date Uploaded' ).' - '.KernelTools::tra( 'descending' ),
	'lc.created_asc'        => KernelTools::tra( 'Date Uploaded' ).' - '.KernelTools::tra( 'ascending' ),
	'lc.last_modified_desc' => KernelTools::tra( 'Last Modified' ).' - '.KernelTools::tra( 'descending' ),
	'lc.last_modified_asc'  => KernelTools::tra( 'Last Modified' ).' - '.KernelTools::tra( 'ascending' ),
];
$gBitSmarty->assign( 'sortOptions', $sortOptions );
$gBitSmarty->assign( 'imageSizes', Bitweaver\Liberty\get_image_size_options( false ));

//vd($_REQUEST);
if (!empty($_REQUEST['fisheyeAdminSubmit'])) {
	// General Settings
	foreach ($formGalleryGeneral as $item=>$data) {
		if( $data['type'] == 'checkbox' ) {
			simple_set_toggle($item, FISHEYE_PKG_NAME);
		} else {
			$gBitSystem->storeConfig($item, $_REQUEST[$item], FISHEYE_PKG_NAME );
		}
	}

	// Gallery List Display Settings
	foreach ($formGalleryListLists as $item=>$data) {
		simple_set_toggle($item, FISHEYE_PKG_NAME);
	}

	// Gallery Display Settings
	foreach ($formGalleryLists as $item => $data) {
		simple_set_toggle($item, FISHEYE_PKG_NAME);
	}

	foreach( [ 'fisheye_list_thumbnail_size', 'fisheye_gallery_default_thumbnail_size', 'default_gallery_pagination', 'rows_per_page', 'cols_per_page', 'total_per_page', 'lines_per_page', 'galleriffic_style', 'fisheye_gallery_default_sort_mode' ] as $key ) {
		$gBitSystem->storeConfig($key, $_REQUEST[$key], FISHEYE_PKG_NAME);
	}

	// Image Display Settings
	foreach ($formImageLists as $item => $data) {
		simple_set_toggle( $item, FISHEYE_PKG_NAME );
	}
	if( !empty( $_REQUEST['default_image_thumbnail_size'] ) ) {
		$gBitSystem->storeConfig('fisheye_image_default_thumbnail_size', $_REQUEST['default_image_thumbnail_size'], FISHEYE_PKG_NAME );
	}

}
